package com.mapper;

import com.pojo.Book;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_books
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_books
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_books
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_books
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    Book selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_books
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_books
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    int updateByPrimaryKey(Book record);
}