package com.pojo;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_books.id
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_books.name
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_books.author
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_books.buytime
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    private Date buytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_books.sid
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_books.id
     *
     * @return the value of tb_books.id
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_books.id
     *
     * @param id the value for tb_books.id
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_books.name
     *
     * @return the value of tb_books.name
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_books.name
     *
     * @param name the value for tb_books.name
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_books.author
     *
     * @return the value of tb_books.author
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_books.author
     *
     * @param author the value for tb_books.author
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_books.buytime
     *
     * @return the value of tb_books.buytime
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public Date getBuytime() {
        return buytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_books.buytime
     *
     * @param buytime the value for tb_books.buytime
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public void setBuytime(Date buytime) {
        this.buytime = buytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_books.sid
     *
     * @return the value of tb_books.sid
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_books.sid
     *
     * @param sid the value for tb_books.sid
     *
     * @mbg.generated Wed Jul 25 13:17:38 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}